# Generated by Django 5.0 on 2024-01-22 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_new_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='demo_video',
            field=models.FileField(upload_to='project/demo_video/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='project/photo/'),
        ),
    ]
